Algoritmo "Troca A&B"
Var
A,B, temp:inteiro
Inicio
escreva("DIGITE O VALOR DE A:")
leia(A)
escreva("DIGITE O VALOR DE B:")
leia(B)
escreva("O VALOR DE A É:")
escreval(A)
escreva("O VALOR DE B É:")
escreval(B)
escreval("AGORA VAMOS TROCAR O VALOR DA VARÍAVEL")
escreval("...")
escreval(".....")
escreval("CONCLUÍDO")
temp<-b
b<-a
a<-temp
escreva("O VALOR DE A É:")
escreval(A)
escreva("E O VALOR DE B É:")
escreval(B)
Fimalgoritmo